name: Build Dev Container

on:
  push:
    branches: [main]
    paths:
      - '.devcontainer/**'
      - '.github/workflows/build-devcontainer.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: Build and (optionally) push dev container image
        uses: devcontainers/ci@v0.3.1900000417
        with:
          imageName: codefastcn/dev-container
          push: always
          platform: linux/arm64
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
