name: Build Dev Container

on:
  push:
    branches: [main]
    paths:
      - '.devcontainer/**'
      - '.github/workflows/build-devcontainer.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and (optionally) push dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: registry.cn-hangzhou.aliyuncs.com/codefast/dev-container
          push: always
          registry: registry.cn-hangzhou.aliyuncs.com
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          # DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
